Extra statically determined fields
ipinfo/swift pull request #5
Opened 2023-11-26 17:07 UTC by muhammadahmadmslm

- [x] Continent
- [x] Country Name
- [x] Currency
- [x] Is EU
- [x] Flag URL / Emoji

2023-11-27 03:32 UTC, UmanShahzad reviewed
Can you point me to an example of how the user will be using the library? Is it the test cases? And if so why is it parsing JSON in there?

2023-12-04 11:08 UTC, UmanShahzad requested changes
Have you run `swiftfmt` or similar on this codebase? Please run it on the entire thing in a separate PR and make a `.sh` script for running it properly in a `scripts/` folder.

2023-12-04 11:08 UTC, UmanShahzad commented on README.md
> +IPINFO.shared.lookupIP(ip: "8.8.8.8") { status, response, msg in
In your test cases I see `getDetail` and here `lookupIP`. Which is it?

2023-12-07 13:05 UTC, muhammadahmadmslm commented on Sources/ipinfoKit/Model/IPResponse/IPResponse.swift
> +    public var description: String {
Yes Brother, Swift provides a built-in way to get a string representation of an object using the String(describing:) initialiser. This initialiser creates a string representation of a value or instance.

```swift
let array = [1, 2, 3]
let stringFromArray = String(describing: array)

let dictionary = ["key": "value"]
let stringFromDictionary = String(describing: dictionary)

class MyClass {
    var property: String
    
    init(property: String) {
        self.property = property
    }
}

let myInstance = MyClass(property: "Hello, World!")

// Using String(describing:) to get the string representation
let stringRepresentation = String(describing: myInstance)

```

2023-12-11 02:43 UTC, UmanShahzad reviewed
I think your swiftfmt has forced real `\t` tab characters. Don't think that's normal in Swift? Please fix!

2023-12-11 02:43 UTC, UmanShahzad commented on Tests/.DS_Store
?

2023-12-11 23:30 UTC, UmanShahzad approved these changes

2023-12-11 23:30 UTC, merged